### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by demist** [Jesaig/mipt_TP#2]
1. Нет схемы архитектуры
2. Вся система в одном файле - это неправильно, должно быть логическое разделение
3. Не должно быть констант в коде. Это должны быть либо отдельный файл ресурсов, либо дефайны, либо статики

Пока оценить архитектуру проекта сложно

p.s. Стоило завести отдельный репозиторий для проекта, а не мешать в другими заданиями

**Comment by demist** [comment]
Замечания исправлены?

**Comment by Jesaig** [comment]
Исправлены, проверьте, пожалуйста.
https://github.com/Jesaig/mipt_TP_Game

**Comment by demist** [comment]
принято

но схему архитектуры стоило бы сделать более подробной
